CREATE TABLE ATTENDEECONTACT (
    AttendeeContactID INT PRIMARY KEY AUTO_INCREMENT,
    AttendeeID INT NOT NULL,
    ContactType VARCHAR(20) NOT NULL,
    ContactValue VARCHAR(100) NOT NULL,
    FOREIGN KEY (AttendeeID) REFERENCES ATTENDEE(AttendeeID) ON DELETE CASCADE
);
