CREATE TABLE EVENT (
    EventID INT PRIMARY KEY AUTO_INCREMENT,
    EventName VARCHAR(100) NOT NULL,
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    Description TEXT NOT NULL,
    Duration INT NOT NULL,
    VenueID INT NOT NULL,
    OrganizerID INT NOT NULL,
    FOREIGN KEY (VenueID) REFERENCES VENUE(VenueID),
    FOREIGN KEY (OrganizerID) REFERENCES ORGANIZER(OrganizerID)
);
