CREATE TABLE FEEDBACK (
    FeedbackID INT PRIMARY KEY AUTO_INCREMENT,
    AttendeeID INT NOT NULL,
    EventID INT NOT NULL,
    Rating INT NOT NULL,
    Comment TEXT NOT NULL,
    FOREIGN KEY (AttendeeID) REFERENCES ATTENDEE(AttendeeID),
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID)
);
