  CREATE TABLE ORGANIZEREMAIL (
    OrganizerEmailID INT PRIMARY KEY AUTO_INCREMENT,
    OrganizerID INT NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    FOREIGN KEY (OrganizerID) REFERENCES ORGANIZER(OrganizerID) ON DELETE CASCADE
);

