CREATE TABLE ORGANIZERPHONE (
    OrganizerPhoneID INT PRIMARY KEY AUTO_INCREMENT,
    OrganizerID INT NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL UNIQUE,
    FOREIGN KEY (OrganizerID) REFERENCES ORGANIZER(OrganizerID) ON DELETE CASCADE
);
