CREATE TABLE REGISTRATION (
    RegistrationID INT PRIMARY KEY AUTO_INCREMENT,
    AttendeeID INT NOT NULL,
    EventID INT NOT NULL,
    FOREIGN KEY (AttendeeID) REFERENCES ATTENDEE(AttendeeID),
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID)
);
