CREATE TABLE TICKET (
    TicketID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    AttendeeID INT NOT NULL,
    EventID INT NOT NULL,
    FOREIGN KEY (AttendeeID) REFERENCES ATTENDEE(AttendeeID),
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID)
);
